module.exports = {
    "RECIPE_EN_US" : {
        "7 and 7": "1 ounce of Seagrams seven whiskey mixed with seven up.",
        "alabama slammer": "three quarters ounce of Southern Comfort, one half ounce of Amaretto, one half ounce of Gin.  Balance with orange juice. Shake, and serve in a tall glass with ice.",
        "americano": "1 ounce of Vermouth, 1 ounce of Campari.  Build with ice in a highball glass and top with Club Soda and a twist",
        "captain and coke": "Pour 1 and a half ounces of Captain Morgans spiced rum into a tall glass filled with ice.  Fill the rest of the glass with cola and garmish with a lime.",
        "b 52": "one third Kahlua, one third Baileys Irish Cream, one third Grand Marnier. Layer in a shot glass",
        "bahama mamma": "1 and a half ounces of dark Rum, 1 and a half ounces of gold Rum, 1 and a half ounces of light Rum, 1 dash of Grenadine, 2 and one half ounces of Orange Juice, 2 ounces of Pineapple Juice, 2 ounces of Sour Mix. Put a dash of grenadine on the bottom of the glass. Fill with cracked ice and add ingredients. Stir very gently before serving.",
        "belfast bomber": "In a shot glass, layer one half ounces of Baileys Irish Cream and one half ounces of Jameson Irish Whiskey. Fill a pint glass three quarters full with Guinness.  Drop shot glass in the pint.",
        "between the sheets": " three quarters ounce of brandy, three quarters ounce of light rum, one half ounce of Cointreau. Shake, Strain, and serve in a Chilled Martini glass.",
        "black russian": "Stir 1 and a half ounces of Vodka and three quarters ounce of Kahlua in a glass filled with ice.  Garnish with a swizzle stick.",
        "bloody mary": "Pour 1 and a half ounces of Vodka over ice in a glass. Fill with Tomato Juice. Add a dash or two of Worcestershire, Lemon, salt, and Tabasco. Stir and garnish with a Celery Stalk.",
        "blow job": "one half Kahlua;  one half Baileys Irish Cream. Layer in a shot glass. Top rim with whipped cream",
        "blue hawaian": "1 ounce of blue Curacao, 1 ounce of light Rum, 1 ounce of Cream of coconut, 2 ounces of Pineapple Juice, 1 whole Maraschino cherry, 1 slice Pineapple, 1 Cup of Ice. Add all ingredients, except garnishes to a blender and blend at high speed. Pour into a highball glass and garnish with the pineapple slice and a cherry.",
        "boilermaker": "Fill Pint glass halfway with beer, 1 ounce of Whiskey in shot glass. Drop shot glass into beer.",
        "brandy alexander": "Pour 1 and a half ounces of Brandy or cognac, one half ounce of Dark Creme de Cacao, 1 ounce of Sweet Cream or Ice Cream. Shake with ice. Strain.",
        "buttery nipple": "three quarters ounce of Buttershots, three quarters ounce of Baileys Irish Cream. Layer in a shot glass.",
        "champagne cocktail": "3 ounces of chilled Champagne,  1 cube of Sugar and a dash Angostura Bitters. Stir ingredients slowly. Garnish with a Lemon Twist",
        "cosmopolitan": "2 ounces of Vodka, one half ounces of Cointreau, juice from a quarter lime, one half ounces of Cranberry Juice. Shake with ice and strain.",
        "cosmo": "2 ounces of Vodka, one half ounce of Cointreau, juice from a quarter lime, one half ounce of Cranberry Juice. Shake with ice and strain.",
        "cuba libre": "1 and a half ounces of Bacardi Rum, Cola, Juice from a quarter Lime. Add Rum to a glass filled with ice. Fill with Cola. Add Lime Juice and stir.",
        "daiquiri": "1 ounce of rum, one half ounce of lime juice. Balance sour mix. Add fruit mix and Blend. Serve in a Tall glass with ice and a lime wedge garnish.",
        "fuzzy navel": "1 and a half ounces of Peach Schnapps, 3 ounces of Orange Juice.  Pour Schnapps over ice in a rocks glass. Fill with OJ and stir well.",
        "gibson": "2 ounces of vodka or gin, one half ounces of lime juice. Shake and strain into chilled Martini glass.  Add lime wedge or twist garnish",
        "gin and tonic": "1 and a half ounces of Gin, Tonic. In a glass filled with ice, add Gin and fill with Tonic. Add a Lime Wedge.",
        "grasshopper": "one half ounce of Green Creme de Menthe, one half ounce of White Creme de Cacao, one half ounce of Cream. Combine in a blender with ice blend until smooth . Strain into a margarita glass.",
        "greyhound": "1 ounce of vodka, balance grapefruit juice. Build in a Highball glass with ice",
        "harvey wallbanger": "1 ounce of Vodka, Orange Juice, one quarter ounce of Liquore Galliano. In a tall glass with ice, add Vodka and fill the glass three quarters full with Orange Juice. Float the Galliano on top.",
        "highball": "1 and a half ounces of American Whiskey, 3 ounces of Gingerale. Combine and stir.",
        "hurricane": "1 and one quarter ounces of Dark Rum, 4 ounces of Pineapple Juice, 2 ounces of Orange Juice, a splash Grenadine. Combine over ice.",
        "irish car bomb": "In a shot glass, layer one half ounce of Baileys Irish Cream and one half ounce of Jameson Irish Whiskey. Fill a pint glass three quarters full with Guinness.  Drop shot glass in the pint.",
        "jack and coke": "1 and a half ounces of jack Daniels Whiskey, 3 ounces of Coca-cola. Combine over ice and stir.",
        "john collins": "1 ounce of whiskey, balance sour mix and Blend. Top with club soda.",
        "jolly rancher": "one half ounce of vodka; one half ounce of triple sec; one half ounce of flavored Puckers. Splash sour mix, grenadine Shake with ice.",
        "kamikaze": "three quarters ounce of vodka; one half ounce of triple sec; one half ounce of lime juice. Shake, and strain into shot glass. Add flavored vodka for variety.",
        "lemon drop": "1 ounce of citrus vodka. Shake and strain in shot glass. Optionally splash sour mix. Add Sugar coated lemon slice.",
        "liquid cocaine": "one third Jagermeister, one third Rumpleminze, one third Bacardi 151.  Layer in shot or cordial glass.",
        "long island ice tea": "one half ounce of Vodka, one half ounce of Rum, one half ounce of Gin, one half ounce of Triple Sec, one half ounce of Tequila, one half ounce of Sour Mix, Cola. Pour everything into a collins glass, splashing cola on tthe top, and stir gently. Garnish with a lemon spiral and a straw.",
        "mai tai": "one half ounce of orange Curacao, 1 ounce of dark rum, 1 ounce of light rum, one third ounce of fresh lime juice, one half ounce of Orgeat Syrup, one sixth ounce of Sugar Syrup. Shake everything except the dark rum in a shaker filled with ice. Strain into a highball glass over crushed ice. Float with the rum and garnish with a pineapple spear, lime peel and a straw.",
        "manhattan": "2 ounces of American or Canadian Whisky, splash Sweet or Dry Vermouth, dah Angostura Bitters. Stir and Garnish with a Cherry.",
        "margarita": "two thirds ounce of Triple Sec, 1 and one quarter ounce of white Tequila, one half ounce of Lemon Juice or Lime juice, 3 pinches Salt. Salt the rim of a coupe glass. Shake all ingredients with ice, strain into the salt-rimmed glass, and serve.",
        "martini": "3 ounces of Gin or Vodka, a dash Extra Dry Vermouth. Shake or stir Gin and Vermouth over ice. Strain and serve in a cocktail glass straight up or over ice. Garnish with a Twist or an olive.",
        "melon ball": "three quarters ounce of melon liqueur, three quarters ounce of vodka. Balance with orange juice and blend.  Serve over ice.",
        "mimosa": "3 ounces of Champagne, 2 ounces of Orange Juice. Combine in a champagne flute and stir.",
        "mojito": "1 and one third ounce of light Rum, Fill with Carbonated Water or Club Soda, 1 ounce of Lime Juice, 2 Lime wedges, 12 pieces of mint leaves, 1 and a half ounces of Sugar Syrup. Gently muddle the lime juice, mint leaves, and sugar syrup together at the bottom of the glass. Fill the glass with ice, then slowly add the rum. Fill with soda and stir gently to bring the leaves upwards into the mixture. Optionally add lime wedges as an addition garnish.",
        "moscow mule": "2 ounces of Vodka, one half large lime squeezed, 2ounces of Ginger Beer. Stir with ice. Garnish with lime half.",
        "negroni": "three quarters ounce of Dry Vermouth, three quarters ounce of Gin, three quarters ounce of Campari. Combine in a rocks glass over ice. Garnish with a Lemon Twist.",
        "old fashioned": "1 Cherry and Orange Slice, one quarter teaspoon of Superfine Sugar, a splash of Club Soda, 1 and a half ounces of American or Canadian Whisky, 2 dashes Angostura Bitters",
        "orange blossom": "1 ounce of gin, balance with orange juice. Serve with ice.",
        "pina colada": "1 and one quarter ounces of Rum, 2 ounces of Unsweetened Pineapple Juice, 2 ounces of Coco Lopez Cream of Coconut. Mix in a shaker and serve over ice, or blend with crushed ice.",
        "red snapper": "one half ounce of Crown Royal, one half ounce of Amaretto, a Splash of cranberry. Shake and strain in shot glass.",
        "rum and coke": "1 and a half ounces of Rum, 3 ounces of Cola. Stir ingredients with ice.",
        "red headed slut": "one half ounce of Jagermesiter, one half ounce of Peach Schnapps, a splash of cranberry. Shake and strain.",
        "rusty nail": "1 ounce of Scotch, 1 ounce of Drambuie. Combine in a rocks glass, add ice, and stir.",
        "salty dog": "1 and a half ounces of Gin or Vodka, 3 ounces of Grapefruit Juice. Mix with ice and pour into a salt-rimmed glass.",
        "scarlett o’ hara": "1 ounce of Southern Comfort. balance cranberry. Serve with ice.",
        "scotch and soda": "1 and a half ounces of Scotch, 3 ounces of Club Soda. Stir with ice.",
        "screwdriver": "2 ounces of Vodka, 4 ounces of Oranger Juice. Add Vodka to a tall glass with ice and fill with Orange Juice.",
        "seabreeze": "2 ounces of Vodka, Grapefruit Juice, Cranberry Juice. Pour Vodka over ice. Fill halfway with Grapefruit juice and top it off with cranberry juice.",
        "sex on the beach": "one half ounce of Vodka, one quarter ounce of Peach Schnaps, one half ounces of Cranberry Juice, one half ounce of Grapefruit Juice, one half ounce of Orange Juice. Combine in a mixing glass. Shake or stir. pour into a shot glass.",
        "sidecar": "one half ounce of cointreau, one half teaspoon of Fresh Lemon Juice, 1 ounce of Remy Martin Cognac, 3 to 4 ice cubes. Combine all ingredients in a shaker and shake vigorously. Strain into a chilled cocktail glass.",
        "so co and lime": "three quarters ounce of Southern Comfort,  one half ounce of lime juice. Shake and strain into a shot glass",
        "spritzer": "3 ounces of Dry White Wine, Club Soda. Pour wine in a glass and fill with soda. Garnish with a Lemon Twist.",
        "surfer on acid": "one half ounce of Jagermeister, one half ounce of Peach Schnapps, one half ounce of Pineapple Juice. Shake over ice and strain into a shot glass.",
        "tequila sunrise": "one half ounce of Grenadine, 1 and a half ounce of Tequila , Orange Juice. Pour Grenadine into a tall glass first. Then add Tequila and fill with ice and Orange Juice. Garnish with an Orange Slice.",
        "tom collins": "1 and a half ounces of Gin, Juice of one half Lemon, 1 teaspoon of Sugar, Club Soda. Shake the first three ingredients and pour over ice. Top with Club Soda.",
        "vampire": "three quarters ounce of vodka, three quarters ounce of Chambord, balance with cranberry. Serve with ice.",
        "vodka and tonic": "1 and a half ounces of Vodka, 3 ounces of Tonic. Stir ingredients with ice in a glass. Garnish with a lime wheel.",
        "whiskey sour": "1 and a half ounces of Whiskey, three quarters ounce of Sweetened Lemon Juice, 1 teaspoon of Superfine Sugar. Shake with ice. Serve straight up or over ice.",
        "white russian": "1 and a half ounces of Vodka, one half ounce of Kahlua, one half ounce of Cream. Shake and serve over ice.",
        "tropical hooter": "1 ounce of melon liquor, 1 ounce of coconut rum, 2 ounces of cranberry juice, 2 ounces of pineapple juice.  Mix ingredients over ice in glass. Shake if preferred."
    }
};